[package]
name = "ws2markdown"
version = "0.1.0"
authors = ["Cthulhux <git@tuxproject.de>"]
edition = "2021"
license = "CDDL-1.1"

[dependencies]
anyhow = "1.0"
pest = "2.7"
pest_derive = "2.7"
rfd = "0.11"
